# Generated by Django 4.2.2 on 2023-06-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='streaming_platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='tv_content.streamingplatform'),
            preserve_default=False,
        ),
    ]
