# Generated by Django 4.2.2 on 2023-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_content', '0004_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='total_num_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
